const input_list = [
  //  'C:/Users/jokn/Desktop/pano/1-10/1/back.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/1/front.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/1/bottom.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/1/left.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/1/right.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/1/top.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/2/back.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/2/bottom.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/2/front.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/2/left.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/2/right.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/2/top.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/10/back.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/10/bottom.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/10/front.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/10/left.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/10/right.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/10/top.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/3/back.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/3/bottom.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/3/front.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/3/left.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/3/right.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/3/top.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/4/back.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/4/bottom.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/4/front.jpg',
  //   'C:/Users/jokn/Desktop/pano/1-10/4/left.jpg',
  // 'C:/Users/jokn/Desktop/pano/1-10/4/right.jpg',
  // 'C:/Users/jokn/Desktop/pano/1-10/4/top.jpg',
  // 'C:/Users/jokn/Desktop/pano/1-10/5/back.jpg',
  // 'C:/Users/jokn/Desktop/pano/1-10/5/front.jpg',
  // 'C:/Users/jokn/Desktop/pano/1-10/5/bottom.jpg',
  // 'C:/Users/jokn/Desktop/pano/1-10/5/right.jpg',
  // 'C:/Users/jokn/Desktop/pano/1-10/5/top.jpg',
  // 'C:/Users/jokn/Desktop/pano/1-10/5/left.jpg',
  // 'C:/Users/jokn/Desktop/pano/1-10/6/back.jpg',
  // 'C:/Users/jokn/Desktop/pano/1-10/6/bottom.jpg',
  // 'C:/Users/jokn/Desktop/pano/1-10/6/front.jpg',
  // 'C:/Users/jokn/Desktop/pano/1-10/6/left.jpg',
  // 'C:/Users/jokn/Desktop/pano/1-10/6/right.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/6/top.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/7/back.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/7/bottom.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/7/front.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/7/left.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/7/right.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/7/top.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/8/back.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/8/bottom.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/8/front.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/8/left.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/8/right.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/8/top.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/9/back.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/9/front.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/9/bottom.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/9/left.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/9/right.jpg',
  'C:/Users/jokn/Desktop/pano/1-10/9/top.jpg'];

const output_list =
  [
    // './pano/1-10/1/back.jpg',
    //   './pano/1-10/1/front.jpg',
    //   './pano/1-10/1/bottom.jpg',
    //   './pano/1-10/1/left.jpg',
    //   './pano/1-10/1/right.jpg',
    //   './pano/1-10/1/top.jpg',
    //   './pano/1-10/2/back.jpg',
    //   './pano/1-10/2/bottom.jpg',
    //   './pano/1-10/2/front.jpg',
    //   './pano/1-10/2/left.jpg',
    //   './pano/1-10/2/right.jpg',
    //   './pano/1-10/2/top.jpg',
    //   './pano/1-10/10/back.jpg',
    //   './pano/1-10/10/bottom.jpg',
    //   './pano/1-10/10/front.jpg',
    //   './pano/1-10/10/left.jpg',
    //   './pano/1-10/10/right.jpg',
    //   './pano/1-10/10/top.jpg',
    //   './pano/1-10/3/back.jpg',
    //   './pano/1-10/3/bottom.jpg',
    //   './pano/1-10/3/front.jpg',
    //   './pano/1-10/3/left.jpg',
    //   './pano/1-10/3/right.jpg',
    //   './pano/1-10/3/top.jpg',
    //   './pano/1-10/4/back.jpg',
    //   './pano/1-10/4/bottom.jpg',
    //   './pano/1-10/4/front.jpg',
    //   './pano/1-10/4/left.jpg',
    // './pano/1-10/4/right.jpg',
    // './pano/1-10/4/top.jpg',
    // './pano/1-10/5/back.jpg',
    // './pano/1-10/5/front.jpg',
    // './pano/1-10/5/bottom.jpg',
    // './pano/1-10/5/right.jpg',
    // './pano/1-10/5/top.jpg',
    // './pano/1-10/5/left.jpg',
    // './pano/1-10/6/back.jpg',
    // './pano/1-10/6/bottom.jpg',
    // './pano/1-10/6/front.jpg',
    // './pano/1-10/6/left.jpg',
    // './pano/1-10/6/right.jpg',
    './pano/1-10/6/top.jpg',
    './pano/1-10/7/back.jpg',
    './pano/1-10/7/bottom.jpg',
    './pano/1-10/7/front.jpg',
    './pano/1-10/7/left.jpg',
    './pano/1-10/7/right.jpg',
    './pano/1-10/7/top.jpg',
    './pano/1-10/8/back.jpg',
    './pano/1-10/8/bottom.jpg',
    './pano/1-10/8/front.jpg',
    './pano/1-10/8/left.jpg',
    './pano/1-10/8/right.jpg',
    './pano/1-10/8/top.jpg',
    './pano/1-10/9/back.jpg',
    './pano/1-10/9/front.jpg',
    './pano/1-10/9/bottom.jpg',
    './pano/1-10/9/left.jpg',
    './pano/1-10/9/right.jpg',
    './pano/1-10/9/top.jpg'];

module.exports = {
  output_list,
  input_list
}